### ISSUE TITLE
Apply f1 score as metrics for training

### ISSUE THREAD

**Issue by billynguyenlss** [google/yggdrasil-decision-forests#101]
How could I apply f1_score in my training procedure? I can do it with tfdf, but could not find similar API in ydf.
Thanks for your help.

**Comment by achoum** [comment]
YDF currently does not compute and report the F1 score.

This could be a feature request.

In the meantime, YDF tends to play well with other ML frameworks. You can for example use [sklearn f1 evaluation code](sklearn.metrics.f1_score) or the [keras one](https://keras.io/api/metrics/classification_metrics/#f1score-class) on the output of YDF's `model.predict(...)`.
