### ISSUE TITLE
[Question] Ignore Columns in Deployed Model?

### ISSUE THREAD

**Issue by rlcauvin** [google/yggdrasil-decision-forests#104]
I want to ignore certain feature columns in the input for both model training and when I invoke the model deployed to an endpoint. I don't want the client of the model to "know" that the model is ignoring the features.

When training the model, I can ignore `user_id` feature as follows:
```
all_features = ["user_id", "age", "gender", "job_title", "label"]
ignored_features = ["user_id", "label"]
features = [feature for feature in all_features if feature not in ignored_features]

df_learner = ydf.GradientBoostedTreesLearner(label="label", features=features, include_all_columns=False)
df_model = df_learner.train(ds=cached_train_ds, valid=cached_test_ds)
```
I can then use `df_model.predict(cached_test_ds)` to make predictions, and it properly ignores the excluded features.

But if I deploy the model to an endpoint using TensorFlow serving (in Amazon SageMaker), I get an error if I try to invoke it with input that includes the features I want to ignore:
```
ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: 
Received server error (500) from primary with message "{"error": "{\n    \"error\": \"Failed
to process element: 0 key: user_id of 'instances' list. Error: INVALID_ARGUMENT: JSON object:
does not have named input: user_id\"\n}"}". See https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-rrrrrr-2#logEventViewer:group=/aws/sagemaker/Endpoints/yyyyyyyyyyyyyyyyyyyy
in account XXXXXXXXXXXXXX or more information.
```
I expected that the deployed model would silently ignore the excluded features.  I could write a custom inference script to drop the excluded features, but it seems YDF should handle it for me, just as it does when I call `df_model.predict(cached_test_ds)`. Shouldn't it?

**Comment by achoum** [comment]
Thanks for the report. This looks like a bug :).

**Comment by achoum** [comment]
In your example, what are "cached_train_ds" and "cached_test_ds" i.e. what are the datasets object?

**Comment by rlcauvin** [comment]
They are instances of tf.data.Dataset. I create them from tensor slices and then batch and cache them.

```
master_ds = tf.data.Dataset.from_tensor_slices(tensor_slices)

master_length = len(master_ds)
train_percent = 0.80
test_percent = 0.20

train_length = int(train_percent * master_length)
test_length = master_length - int(train_percent * master_length)
train_ds = master_ds.take(train_length)
test_ds = master_ds.skip(train_length).take(test_length)

cached_train_ds = train_ds.batch(512).cache()
cached_test_ds = test_ds.batch(128).cache()
```
The tensor slices are of the form `{"user_id": [...], "age": [...], "gender": [...], "job_title": [...], "label": [...]}`

**Comment by rlcauvin** [comment]
As of the latest `ydf-0.6.0` release, this problem seems to be fixed. I have deployed a model that I trained with certain features to ignore, and the deployed model is ignoring those features during inference as well.

**Comment by rstz** [comment]
Great, thank you for reporting, closing this
