### ISSUE TITLE
building off external hard drive

### ISSUE THREAD

**Issue by jdubz93** [google/yggdrasil-decision-forests#11]
```
root@mocha-eft:/mnt/sdcard/yggdrasil-decision-forests# bazel --output_user_root=/mnt/sdcard/install build //examples:beg
inner_cc --config=linux_cpp17 --config=linux_avx2
```

```
Extracting Bazel installation...
FATAL: failed to create installation symlink '/mnt/sdcard/install/32ee77bc3907dda3edc97c30cd47096e/install': (error: 1): Operation not permitted
root@mocha-eft:/mnt/sdcard/yggdrasil-decision-forests#
```

Does anyone know if you can use bazel on a external hard disk. For example say I mounted an sd card on my raspberry pi. Can I use bazel to build from the mounted drive? I know bazel uses java which can cause some weird permission issues im assuming.

**Comment by achoum** [comment]
I don't have the knowledge to answer your question, but to run Bazel on a Raspberry pie, I would try the first steps of the [Building TensorFlow for Raspberry Pi tutorial](https://github.com/samjabrahams/tensorflow-on-raspberry-pi/blob/master/GUIDE.md).

Yggdrasil DF being much simpler to compile than TF (much less dependencies), this should effectively be even easier than compiling TF :).
