### ISSUE TITLE
Be clear in docs which architectures are supported

### ISSUE THREAD

**Issue by CodingDoug** [google/yggdrasil-decision-forests#111]
I tried to get ydf to work on my M1 mac, and only after a couple of hours struggling with this did I find that this was never going to work.  I also tried on a Linux arm64 VM on the same machine.  There was nothing telling me that neither of these things were ever going to work as expected.

What's worse is that installing ydf is actually possible on these platforms, but it just gets a very old version of the library that was built for one of those platforms.  As such, one is very much fooled into thinking that they are on a good path (unless they happen to notice the version).

There really needs to be a clear mention of the platforms that are or are not supported at the top of the docs, maybe in the getting started guide.

Ideally, it would be great to actually support arm platforms. It's not clear why that was dropped.

**Comment by achoum** [comment]
Hi Doug,

Thank you for your recommendation and sorry to head about your poor experience.
We'll add a section listing actively supported platforms and Python versions.

M1 and ARM64 support haven't been dropped, but their builds are still experimental. This means they're triggered manually. Unfortunately, the engineer responsible for these has been out of office for some time. However, they'll be back soon, so you can expect to see those versions updated likely soon.

**Comment by rstz** [comment]
Arm64 support has been restored with Version 0.7.0 and will be supported going forward.

**Comment by rstz** [comment]
Added the inforamtion to the FAQ https://ydf.readthedocs.io/en/latest/faq/#adding-an-empty-column-to-my-model-changes-its-quality-why:~:text=Which%20architectures%20are%20supported%20by%20YDF%3F
