### ISSUE TITLE
model.predict requires headers

### ISSUE THREAD

**Issue by jerryajay** [google/yggdrasil-decision-forests#124]
Hello,
    When trying to use `model.predict`, I have to pass the 'column names' along with the data. For example, when passing in just one set of features (1 row , 216 columns), I get the Error message:
```
A dataset can be one of the following:
  1. A dictionary of string (column names) to column values. The values of a column can be a list of int, float, bool, str, bytes, or a numpy array. A 2D numpy array is treated as a multi-dimensional column.
  2. A Pandas DataFrame.
  3. A YDF VerticalDataset created with `ydf.create_vertical_dataset`. This option is the most efficient when the same dataset is used multiple times.
  4. A batched TensorFlow Dataset.
  5. A typed path to a csv file e.g. "csv:/tmp/dataset.csv". See supported types below. The path can be sharded (e.g. "csv:/tmp/dataset@10") or globbed ("csv:/tmp/dataset*").
```
Why should the 'column names' be passed for 'prediction' tasks? Please let me know a workaround.

**Comment by rstz** [comment]
Hi,
YDF needs a name for every column. If your data is e.g. just a numpy matrix, you can just wrap it in a Python dictionary, e.g.
```python
# X_train.shape
# > (200233, 10)
# y_train.shape
# > (200233,)
ydf.RandomForestLearner(label="label").train({"features": X_train, "label": y_train})
```
The actual features will then be `features.00_of_10`, `features.01_of_10`, ...

**Comment by rstz** [comment]
(Added after submitting too early):
It is important to use the same feature names you used in training during prediction. In the above example, that would be

```
model.predict({"features": X_test})
```

You can see the feature names used by the model in `model.input_features()`

**Comment by jerryajay** [comment]
I asked specifically for 'prediction' scenarios. During deployment on production pods, my model does not have access to column names.
