### ISSUE TITLE
Does the ydf.RandomSearchTuner handle all of these parameters?

### ISSUE THREAD

**Issue by salamanders** [google/yggdrasil-decision-forests#125]
Does the tuner handle things like forest_extraction and shrinkage? I'm betting the tuner handles num_trees, but the docs mentioned that 'DART' might be more accurate in some cases.
Also, any benefit from starting with any of these commented back in to give the tuner a head-start?

```python
learner_gbt = ydf.GradientBoostedTreesLearner(
    **templates_gbt["better_defaultv1"],
    # task=ydf.Task.CLASSIFICATION,
    # features=[col for col in combined_df.columns if col not in ['ID', 'target']],
    # num_trees=1000,
    # forest_extraction='DART',
    # shrinkage=0.02,
    tuner=tuner,
    label="target")
```

**Comment by rstz** [comment]
The tuner is able to handle arbitrary hyperparameters if asked to consider them in the search space
```
tuner = ydf.RandomSearchTuner(num_trials=50)
tuner.choice("shrinkage", [0.2, 0.1, 0.05])
tuner.choice("forest_extraction", ["DART", "MART"])
learner = ydf.GradientBoostedTreesLearner(
    label="income",
    num_trees=100, # Used for all the trials.
    tuner=tuner,
)
model =learner.train(train_ds)
```

If you don't want to configure the search space manually, you can use the automatic search space, as described in the last part of the [tuner tutorial](https://ydf.readthedocs.io/en/latest/tutorial/tuning/).

**Comment by salamanders** [comment]
Cool, if I'm understanding: to give the tuner the most flexibility, I wouldn't tell it anything, and I wouldn't specify anything in the `ydf.GradientBoostedTreesLearner` call.  So for the widest possible search space, I'd use the following?

```python
tuner = ydf.RandomSearchTuner(
    num_trials=100,
    # parallel_trials=5, If CPU is maxed out, no need to run in parallel.
    automatic_search_space=True)

templates_gbt = ydf.GradientBoostedTreesLearner.hyperparameter_templates()

learner_gbt = ydf.GradientBoostedTreesLearner(
    **templates_gbt["better_defaultv1"],
    # num_trees=2000, # optimized by the tuner
    # forest_extraction='DART', # optimized by the tuner
    # loss='MULTINOMIAL_LOG_LIKELIHOOD', # optimized by the tuner
    # shrinkage=0.02, # optimized by the tuner
    tuner=tuner,
    label="target")
```

**Comment by rstz** [comment]
Kind of :)

I realize now that `automatic_search_space` is not as well-documented as it maybe should be. Choosing this parameter pre-fills the tuner with possible choices that generally make sense for the learner you've chose. It does not contain all the hyperparameters and we don't have great documentation on which ones are actually used. I'll try to add this to the documentation! 

One important parameter that is not included in `automatic_search_space` is `num_trees`, since a larger number of trees will almost always increase quality but also inference time and model size (esp. for Random Forests). If you want to tune the number of trees, you'll have to use something like
```
tuner = ydf.RandomSearchTuner(num_trials=5, automatic_search_space=True)
tuner.choice("num_trees", [100, 200, 300, 400, 500, 600, 700, 800])
```

**Comment by salamanders** [comment]
When running via command line instead of colab, I found

> HParams: fields { name: "split_axis" value { categorical: "SPARSE_OBLIQUE" } } fields { name: "sparse_oblique_projection_density_factor" value { real: 5 } } fields { name: "sparse_oblique_normalization" value { categorical: "NONE" } } fields { name: "sparse_oblique_weights" value { categorical: "BINARY" } } fields { name: "categorical_algorithm" value { categorical: "RANDOM" } } fields { name: "growing_strategy" value { categorical: "BEST_FIRST_GLOBAL" } } fields { name: "max_num_nodes" value { integer: 32 } } fields { name: "sampling_method" value { categorical: "RANDOM" } } fields { name: "subsample" value { real: 1 } } fields { name: "shrinkage" value { real: 0.05 } } fields { name: "min_examples" value { integer: 7 } } fields { name: "use_hessian_gain" value { categorical: "false" } } fields { name: "num_candidate_attributes_ratio" value { real: 1 } }

Which didn't include `forest_extraction` but maybe not a big deal.

I'm keeping `**templates_gbt["better_defaultv1"],` unless you say not to, and adding `tuner.choice("num_trees"`

```python

tuner = ydf.RandomSearchTuner(
    num_trials=100,
    parallel_trials=2,
    automatic_search_space=True)
tuner.choice("num_trees", [100, 200, 400, 600, 800, 1200, 1600])

templates_gbt = ydf.GradientBoostedTreesLearner.hyperparameter_templates()

learner_gbt = ydf.GradientBoostedTreesLearner(
    **templates_gbt["better_defaultv1"],
    tuner=tuner,
    label="target")
```

**Comment by rstz** [comment]
Great, let me know if there's more questions
