### ISSUE TITLE
Plots not showing sparse  split atrribute

### ISSUE THREAD

**Issue by marquisthunder** [google/yggdrasil-decision-forests#128]
Dear ydf developers,
    Hope this get you well. I have a question about the plot_otree method not showing split condition when using oblique tree model (SPARSE_OBLIQUE)
```python
learner = ydf.GradientBoostedTreesLearner(
   ...:   label='label',
   ...:   split_axis="SPARSE_OBLIQUE",
   ...:   sparse_oblique_normalization="MIN_MAX",
   ...:   sparse_oblique_num_projections_exponent=1.0,
   ...:   ).train(pd.concat([x_train, y_train], axis=1))
 model.get_tree(0)

Out[4]: Tree(root=NonLeaf(value=None, condition=NumericalHigherThanCondition(missing=False, score=0.0, attribute=3, threshold=95.69999694824219), pos_child=Leaf(value=RegressionValue(num_examples=0.0, value=-0.4674617052078247, standard_deviation=None)), neg_child=Leaf(value=RegressionValue(num_examples=0.0, value=0.3032335340976715, standard_deviation=None))))
```
The split condition is always sparse split instead of real attribute name.
![image](https://github.com/user-attachments/assets/280017e8-5409-45ff-93ec-2d0219afd374)

**Comment by rstz** [comment]
Hi, thank you for reporting this. The name of the attributes and their weights are shown as tooltips if you hover with the mouse over the three dots. Since there are (often) multiple attributes involved, the condition can be quite large and we did not want to clutter the plot too much. Does this work for you?

**Comment by marquisthunder** [comment]
thanks, it works well.
