### ISSUE TITLE
validation_ratio or validation_set_ratio

### ISSUE THREAD

**Issue by salamanders** [google/yggdrasil-decision-forests#131]
Docs mention https://ydf.readthedocs.io/en/latest/guide_how_to_improve_model/#other-impactful-hyper-parameters-for-gbt validation_set_ratio, but I think the actual parameter is `validation_ratio`

**Comment by rstz** [comment]
Thank you for reporting, I'll fix this :)

(fun coincidence - someone else reported the same issue yesterday evening on a different channel)
