### ISSUE TITLE
Install Error with pip: Windows 10

### ISSUE THREAD

**Issue by patrickjedlicka** [google/yggdrasil-decision-forests#138]
Hello Team,

I get this error for installing ydf via pip on Windows 10:

```
Microsoft Windows [Version 10.0.22631.4317]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\myself>pip install ydf -U
ERROR: Ignored the following yanked versions: 0.0.0
ERROR: Could not find a version that satisfies the requirement ydf (from versions: none)
ERROR: No matching distribution found for ydf
```

Is ydf not supporting windows?

**Comment by rstz** [comment]
Hi, we do provide Windows builds for Python 3.8 - 3.11 via [Pypi](https://pypi.org/project/ydf/0.8.0/#files). Can you confirm that you're using one of these Python versions?

**Comment by patrickjedlicka** [comment]
I works now. There must have been something messed up with Python. Sorry for bothering
