### ISSUE TITLE
Compiling on Mac

### ISSUE THREAD

**Issue by Timo3as** [google/yggdrasil-decision-forests#14]
Hi all,

I am currently experimenting with Yggdrasil and trying to compile it on macOS Big Sur. On Linux it runs without problems.

My setup:
- Apple clang version 13.0.0 (clang-1300.0.29.3) or gcc/g++ (Homebrew GCC 9.4.0) 9.4.0
- bazel 4.0.0 (did tried bazelisk aswell)
- Python 3.9.5
- numpy Version: 1.21.3

I tried different flags out of the .bashrc for config macos and linux. 

Whatever I do the compiler crashes with following error:

yggdrasil_decision_forests/utils/bitmap.cc:198:12: error: out-of-line definition of 'BitWriter' does not match any declaration in 'yggdrasil_decision_forests::utils::bitmap::BitWriter'
BitWriter::BitWriter(const uint64_t size, std::string* bitmap)

In other branches you have different versions of the BitWriter Class. The ones not in main are adding ~BitWriter(); in Public of BitWriter class in bitmap.h. 
I added this but got same result. 

So can you tell me. what I am doing wrong? Is there a way to get it running on mac?

Thanks so much for response.

Best regards,

Timo

Edit 1:

We seem to have found the error. 

Since in [bitmap.h](https://github.com/google/yggdrasil-decision-forests/blob/7101429888378f26f0cb523eb69ccbe4ec9e5f2f/yggdrasil_decision_forests/utils/bitmap.h#L155) the declaration is as follows:

`BitWriter(size_t size, std::string* bitmap);`

We have another type in [bitmap.cc](https://github.com/google/yggdrasil-decision-forests/blob/7101429888378f26f0cb523eb69ccbe4ec9e5f2f/yggdrasil_decision_forests/utils/bitmap.cc#L198):

`BitWriter::BitWriter(const uint64_t size, std::string* bitmap)`

After changing uint64_t size to size_t size in [bitmap.cc](https://github.com/google/yggdrasil-decision-forests/blob/7101429888378f26f0cb523eb69ccbe4ec9e5f2f/yggdrasil_decision_forests/utils/bitmap.cc#L198), compiling on macOS worked.

**Comment by achoum** [comment]
Hi Timo3as,

Thanks a lot for the alert + solution :).
The fix will propagate soon.

M.

**Comment by achoum** [comment]
Fixed in b1f268dffc3255c71d5b25c163dbfa447861c818.
