### ISSUE TITLE
platforms dependency

### ISSUE THREAD

**Issue by amir2040** [google/yggdrasil-decision-forests#17]
Hi, 
i was following installation instruction but build failed with this error:
```
 ERROR: .../external/com_google_absl/absl/BUILD.bazel:84:15: no such target '@platforms//cpu:wasm32': target 'wasm32' not declared in package 'cpu' defined by .../external/platforms/cpu/BUILD and referenced by '@com_google_absl//absl:platforms_wasm32'
ERROR: While resolving configuration keys for @com_google_absl//absl:wasm_3: Analysis failed
ERROR: While resolving configuration keys for @com_google_absl//absl/synchronization:synchronization: Analysis failed
ERROR: Analysis of target '//yggdrasil_decision_forests/cli:cli_test' failed; build aborted: Analysis failed
```
but it resolved by adding this to yggdrasil/yggdrasil-decision-forests/third_party/absl/workspace.bzl:
```
http_archive(
        name = "platforms",
        sha256 = "b601beaf841244de5c5a50d2b2eddd34839788000fa1be4260ce6603ca0d8eb7",
        strip_prefix = "platforms-98939346da932eef0b54cf808622f5bb0928f00b",
        urls = ["https://github.com/bazelbuild/platforms/archive/98939346da932eef0b54cf808622f5bb0928f00b.zip"],
    )
```
ububtu 18.04, bazel 4.0.0
bazel build  //yggdrasil_decision_forests/cli/...:all --config=linux_cpp17 --config=linux_avx2 --repo_env=CC=gcc-9 --copt=-mavx2 --config=use_tensorflow_io --define=no_absl_statusor=1

is it because of some dependency changes or have i done sth wrong?

**Comment by achoum** [comment]
Hi,

Thanks for the alert and the proposed fix. I'll update the repo.

This error is triggered by this [recent change](https://github.com/abseil/abseil-cpp/commit/eb3db08cb3a4faf2aa09a2ba4a30b442457f36cf) to absl. Unfortunately, adding the `bazel_skylib` rule mentioned in this change is not (yet?) enough. In other words, you did nothing wrong :).
