### ISSUE TITLE
Yggdrasil on the GPU

### ISSUE THREAD

**Issue by JoseAF** [google/yggdrasil-decision-forests#30]
Hi and Happy New Year!

In one of our chats, it was mentioned that:

"Inference on GPU of decision forests is very fast (but it requires a GPU). In some old experiments I did, I observed a ~30x speed-up when comparing the CPU version (single-threaded) with a basic GPU implementation"

Given such an improvement on speed, I'd be interested in exploring a GPU implementation. Currently I use a GBT model with the quickscorer algorithm. How should I go about changing this into a GPU implementation? Here I'm just looking for general guidelines since I haven't seen any obvious ways of doing this in the documentation. Are there any flags that I can set (either when compiling the lib or during implementation) to facilitate GPU compilation? Does the quickscorer algorithm allow for GPU implementation? I've read that specific engines are tied up to specific hardware (e.g. GPU), but I'm not sure if this also applies to a GradientBoostedTreesLearner?

Thanks in advance for your help.

**Comment by rstz** [comment]
Hi,

happy new year to you as well!

Unfortunately, our experiments with Yggdrasil on GPU have not yet been productionized / made available to the public, so there is nothing to try out yet. We hope to find time and resources to add GPU-code to Yggdrasil at some point, but we do not have a timeline for this.

**Comment by JoseAF** [comment]
@rstz That's ok then - thanks for the quick reply!

**Comment by JoseAF** [comment]
A quick follow up, if you don't mind? 

The ~30x speedup mentioned above is in comparison to single threaded CPU. Might that mean that we can expect ~2x speedup compared to a 16 core CPU (using multithreading)? Or ~5x speedup compared to a 6 core CPU?

Thanks.

**Comment by Arnold1** [comment]
hi @JoseAF do you have some code to share which you run on a gpu?
