### ISSUE TITLE
Saving and loading models trained using quickscorer

### ISSUE THREAD

**Issue by JoseAF** [google/yggdrasil-decision-forests#32]
Hi

I'm working on saving and loading models to file. I have a GradientBoostedTreesBinaryClassificationQuickScorerExtended model and am using the model_library SaveModel/LoadModel to save/load it to/from a directory. When doing this, the library creates a directory with 2 files, a header and a data_spec. I'm not sure whether these contain the whole trained model, but I suspect not, because when I load the model (and cast it to GradientBoostedTreeModel and create the specialized model GradientBoostedTreesBinaryClassificationQuickScorerExtended), I seem to have lost the actual trees as shown when calling DescriptionAndStatistics (the metadata is still there though). Also, this loaded model is not able to predict anymore. Do these SaveModel and LoadModel methods work correctly with these kind of specialized models or should I be taking a different approach here?

Thanks for your help.

**Comment by kanchanchy** [comment]
Hi @JoseAF, Could you please let me know how you ran the quick scorer extended model? There is a test file quick_scorer_extended_test.cc, but it creates a toy model on a toy dataset. I want something similar to the examples available in beginner_cc, but that example does not show how to run the quick scorer algorithm.

I need to train a GradientBoostedTreesBinaryClassification on a loaded CSV data and convert the trained model to GradientBoostedTreesBinaryClassificationQuickScorerExtended model to perform inference. Can anyone guide me on this?

**Comment by achoum** [comment]
Similar issue as https://github.com/google/yggdrasil-decision-forests/issues/31
