### ISSUE TITLE
features question

### ISSUE THREAD

**Issue by Arnold1** [google/yggdrasil-decision-forests#36]
Hi,

how are categorical features implemented in yggdrasil-df - are they kept as strings or converted? Anything i need to know of when using categorical features compared to numerical features? For example If I have url's as a categorical feature with 10k unique strings or more...

from the docs - are they really stored as integers?
```
CATEGORICAL: A categorical value. Generally for a type/class with a finite set of possible values
without ordering.
For example, the color RED in the set {RED, BLUE, GREEN}. Can be a string or an integer.
Internally, categorical values are stored as int32 and should therefore be smaller than ~2B
```

Thanks

**Comment by achoum** [comment]
Hi,

By default, categorical features are consumed with the CART algorithm and produce "in-set conditions" (check table 2 on [this page](https://developers.google.com/machine-learning/decision-forests/conditions) for the list of common tree conditions). You can choose another algorithm to handle categorical features with the [categorical_algorithm](https://ydf.readthedocs.io/en/latest/hyper_parameters.html#id5) hyper-parameter. categorical_algorithm="RANDOM" is an alternative to the CART algorithm that often gives good results.

While categorical features are represented as integers (+ an optional dictionary) internally, categorical features are not treated as numerical features.

Categorical-set features are entirely different from categorical features (different representation, different learning algorithm). Categorical-set features as consumed with [this algorithm](https://arxiv.org/abs/2009.09991).

I hope this helps.
