### ISSUE TITLE
getting protobuf downgrading issue

### ISSUE THREAD

**Issue by 1kaiser** [google/yggdrasil-decision-forests#38]
```
######################$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$<<< tensorflow model
#Copy and execute the following code in a new Google Colab notebook launch to run the model.
!python -m pip install tensorflow tensorflow_decision_forests -U -qq

# Transfer the model from Google Drive to Colab
from google.colab import drive
drive.mount("/content/gdrive")
!cp "/content/gdrive/My Drive/simple_ml_for_sheets/Ice height from bands" ydf_model
  
# Prepare and load the model with TensorFlow
import tensorflow as tf
import tensorflow_decision_forests as tfdf

tfdf.keras.yggdrasil_model_to_keras_model("ydf_model", "tfdf_model")
model = tf.keras.models.load_model("tfdf_model")
######################$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$<<< tensorflow model
```

**output from google colab**

```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 462.5/462.5 KB 18.2 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-metadata 1.12.0 requires protobuf<4,>=3.13, but you have protobuf 4.22.1 which is incompatible.
Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-10-257986a1557a>](https://localhost:8080/#) in <module>
     17 # Prepare and load the model with TensorFlow
     18 import tensorflow as tf
---> 19 import tensorflow_decision_forests as tfdf
     20 
     21 tfdf.keras.yggdrasil_model_to_keras_model("ydf_model", "tfdf_model")

8 frames
[/usr/local/lib/python3.9/dist-packages/google/protobuf/descriptor.py](https://localhost:8080/#) in __new__(cls, name, index, number, type, options, serialized_options, create_key)
    794                 type=None,  # pylint: disable=redefined-builtin
    795                 options=None, serialized_options=None, create_key=None):
--> 796       _message.Message._CheckCalledFromGeneratedFile()
    797       # There is no way we can build a complete EnumValueDescriptor with the
    798       # given parameters (the name of the Enum is not known, for example).

TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

```

**Comment by 1kaiser** [comment]
<html>
<body>
<h3 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Compatibility table</h3><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The following table shows the compatibility between<span> </span><code style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; padding: 0.2em 0.4em; margin: 0px; white-space: break-spaces; background-color: var(--color-neutral-muted); border-radius: 6px;">tensorflow_decision_forests</code><span> </span>and its dependencies:</p>

tensorflow_decision_forests | tensorflow
-- | --
1.1.0 - 1.2.0 | 2.11.0
1.0.0 - 1.0.1 | 2.10.0 - 2.10.1
0.2.6 - 0.2.7 | 2.9.1
0.2.5 | 2.9
0.2.4 | 2.8
0.2.1 - 0.2.3 | 2.7
0.1.9 - 0.2.0 | 2.6
0.1.1 - 0.1.8 | 2.5
0.1.0 | 2.4

<ul dir="auto" style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box;"><em style="box-sizing: border-box;">Solution #2:</em><span> </span>Wrap your preprocessing function into</li></ul>
</body>
</html>

![image](https://user-images.githubusercontent.com/26379748/227101011-1136dde2-75f5-46b5-a4d7-f4f07ae5e73c.png)

**Comment by rstz** [comment]
Hi,

Thank you for the report, I'll have a look. Most likely, this is indeed due to incompatibility between TF 2.12.0 and the current TF-DF - as you can see, TF-DF has not yet been updated on PyPi, but we should get to this very soon.

Best,
Richard

**Comment by 1kaiser** [comment]
i got to get it working ✅ by >>> removing the **tensorflow** install command
```
######################$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$<<< tensorflow model
#Copy and execute the following code in a new Google Colab notebook launch to run the model.
!python -m pip install tensorflow_decision_forests -U -qq

# Transfer the model from Google Drive to Colab
from google.colab import drive
drive.mount("/content/gdrive")
!cp "/content/gdrive/My Drive/simple_ml_for_sheets/Ice height from bands" ydf_model
  
# Prepare and load the model with TensorFlow
import tensorflow as tf
import tensorflow_decision_forests as tfdf

tfdf.keras.yggdrasil_model_to_keras_model("ydf_model", "tfdf_model")
model = tf.keras.models.load_model("tfdf_model")
######################$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$<<< tensorflow model
```
