### ISSUE TITLE
extract model input features with dtypes

### ISSUE THREAD

**Issue by Arnold1** [google/yggdrasil-decision-forests#41]
hi,

if i run tensorflow saved_model_cli, you see 3 inputs: DT_INT64, DT_STRING, DT_FLOAT and their corresponding feature names and 1 output:
```
$ saved_model_cli show --dir ./ --tag_set serve --signature_def serving_default
The given SavedModel SignatureDef contains the following input(s):
  inputs['foo'] tensor_info:
      dtype: DT_INT64
      shape: (-1)
      name: serving_default_foo:0
  inputs['bar'] tensor_info:
      dtype: DT_STRING
      shape: (-1)
      name: serving_default_bar:0
  inputs['foobar'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1)
      name: serving_default_foobar:0
The given SavedModel SignatureDef contains the following output(s):
  outputs['output_1'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, 1)
      name: StatefulPartitionedCall:0
Method name is: tensorflow/serving/predict
```

im trying to get the input feature names + datatypes as shown above - is there a way to get it from the model using this api? i only managed to read the input feature names so far:
```
package main

import (
	"log"
	"fmt"
	"github.com/google/yggdrasil-decision-forests/yggdrasil_decision_forests/port/go/model/io"
)

func main() {
	modelPath := "../foo/tf-model/assets"
	model, err := io.LoadModel(modelPath)
	if err != nil {
		log.Fatalf("Cannot load model. %v", err)
	}

	// Get Dataspec from the rfModel
	dataspec := rfModel.Dataspec()

	// Extract feature information
	for i, featureName := range dataspec.GetColumns() {
		fmt.Println(i, featureName.GetName(), featureName.GetType())
	}
}
```

here is what i get - how can i map that to DT_INT64, DT_STRING, DT_FLOAT as shown above for the saved_model_cli? why is saved_model_cli showing 3 dtypes while in yggdrasil you only shows 2 dtypes (numeric = float, categorical = string)?
```
0 foo NUMERICAL
1 bar CATEGORICAL
2 foobar NUMERICAL
3 __LABEL NUMERICAL
```

**Comment by janpfeifer** [comment]
hi @Arnold1 , sorry I just noticed this issue.

I played around a bit with it here:

https://colab.research.google.com/drive/1pn0dfGDLO1ORch-khJqB936Tx043o8bd?usp=sharing

But understand that actual decision forests algorithms are all Yggdrasil (YDF). The TensorFlow is just a wrapper around YDF, and the dtypes are just constructs of that glue code.

The Go API uses the underlying YDF types (and ignores the TensorFlow signature so to say), either a `float32` for numerical values or `uint32` for categorical (more recently we have `uint8` categorical features in YDF as well for speed, but those haven't been exposed in the Go API).

I hope this helps.

cheers

ps.: I'm wondering if this is one of those [xy problem](https://xyproblem.info/) situations.

**Comment by Arnold1** [comment]
hi @janpfeifer ok - thanks for the info. where is the string than converted to a uint32 than inside tensorflow?

if i use a categorical feature in YDF i will also need to pass a string as an input - which than is mapped to a uint32 somewhere inside the YDF with some mapping table?

**Comment by janpfeifer** [comment]
hi @Arnold1 ,

Internally Categorical values are "dense" ints (`uint32`), start start from 0 to the number of categories. And the API contains the dictionary from the original string value to the corresponding reserved value.

When setting the values of the examples (the input for a prediction), one can provide directly the `uint32` value (using `SetCategorical`) or use the original string value, that will be converted to `uint32` using the dictionary mapping -- using the `SetCategoricalFromString` method.

Apologies if you already got this, just to make sure we are on the same page.

Now, unfortunately, the dictionary of the known strings was not made public originally, so we cannot, for instance, list the known categorical value, or, for instance, add variations, if we wanted that. Probably it was a typo from the original version, but I created PR #43 for that.

For categorical values, a common technique to use (both in decision forests and in neural networks) is to limit the vocabulary size to only the top N most common values, or only to the values that show up in at least some X number of examples. All other values seen in training are replaced by this special value called "out-of-vocabulary". It's a wild-card value that is used, for instance, for categorical values never seen before. For instance, let's say a categorical feature that is a city. You may want to know about the top 1000 cities, and all the rest of the cities be clumped together into this "out-of-vocabulary" value. This will make the model handle well if, during inference, it sees the name of a new small city it has never seen before.

I hope it makes sense. Notice that "out-of-vocabulary" (meaning the categorical feature has a value that was not seen before) means something different than "missing value" (meaning the feature is missing information about the city, in our example).

**Comment by Arnold1** [comment]
> hi @Arnold1 ,
> 
> Internally Categorical values are "dense" ints (`uint32`), start start from 0 to the number of categories. And the API contains the dictionary from the original string value to the corresponding reserved value.
> 
> When setting the values of the examples (the input for a prediction), one can provide directly the `uint32` value (using `SetCategorical`) or use the original string value, that will be converted to `uint32` using the dictionary mapping -- using the `SetCategoricalFromString` method.
> 
> Apologies if you already got this, just to make sure we are on the same page.
> 
> Now, unfortunately, the dictionary of the known strings was not made public originally, so we cannot, for instance, list the known categorical value, or, for instance, add variations, if we wanted that. Probably it was a typo from the original version, but I created PR #43 for that.
> 
> For categorical values, a common technique to use (both in decision forests and in neural networks) is to limit the vocabulary size to only the top N most common values, or only to the values that show up in at least some X number of examples. All other values seen in training are replaced by this special value called "out-of-vocabulary". It's a wild-card value that is used, for instance, for categorical values never seen before. For instance, let's say a categorical feature that is a city. You may want to know about the top 1000 cities, and all the rest of the cities be clumped together into this "out-of-vocabulary" value. This will make the model handle well if, during inference, it sees the name of a new small city it has never seen before.
> 
> I hope it makes sense. Notice that "out-of-vocabulary" (meaning the categorical feature has a value that was not seen before) means something different than "missing value" (meaning the feature is missing information about the city, in our example).

i was hoping to call a function GetCategoricalDtype() which tells me that the categorical feature is a string and i need to call SetCategoricalFromString. but that does not exist right?

**Comment by janpfeifer** [comment]
Yes, so there are no string categorical type internally, categorical features are always `uint32` -- so there is no need of a `GetCategoricalDType` (from YDF perspective). 

The strings are just aliases created automatically from the values seen in training, if the original dtype in training was string.

**Comment by Arnold1** [comment]
you i could check if spec.Dictionary exists and infer that i need to call SetCategoricalFromString?

**Comment by achoum** [comment]
Yes.

The `Dictionary` exists if and only if the model is trained with string categories. Checking for the existence of the dictionary is a reliable (but indirect) way to test if a specific column of the training dataset contained integers or strings.

Also, SetCategoricalFromString is only available if the dictionary [is present](https://github.com/google/yggdrasil-decision-forests/blob/55feaff949643db1b3dd3d4672ad618694c926bd/yggdrasil_decision_forests/port/go/serving/example/example.go#L254C10-L254C20).
