### ISSUE TITLE
How to compile examples out of bazel

### ISSUE THREAD

**Issue by andrea-cassioli-maersk** [google/yggdrasil-decision-forests#46]
I am working on integrating yggdrasil-decision-forests in a C++ application, which is compiled via CMake.

As a first steps, I am trying to compile the full example pointed in https://ydf.readthedocs.io/en/latest/cpp_serving.html, getting the following error:

```
➜  yggdrasil-decision-forests git:(main) ✗ g++ examples/beginner.cc --std=c++17 -I./  
In file included from examples/beginner.cc:46:
./yggdrasil_decision_forests/dataset/data_spec.h:32:10: fatal error: 'yggdrasil_decision_forests/dataset/data_spec.pb.h' file not found
#include "yggdrasil_decision_forests/dataset/data_spec.pb.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

how to deal with the `pb.h`?

**Comment by rstz** [comment]
The `pb.h` files are [Protobuf headers](https://protobuf.dev/). Protobufs are used internally by YDF for message passing and model storage. The `pb.h` files are compiled from the `.proto` files with the protoc compiler. 

With bazel, compilation of the protobufs is configured to be automatic. I haven't used CMake with Protobuf but it looks possible to integrate it with cmake ([stackoverflow instructions](https://stackoverflow.com/questions/20824194/cmake-with-google-protocol-buffers)) or to compile manually [official tutorial](https://protobuf.dev/getting-started/cpptutorial/).

Let me know if this helps

**Comment by andrea-cassioli-maersk** [comment]
OK, I see. I am a bit familiar with compiling protobuf file, I'll give it a try manually for now

**Comment by rstz** [comment]
Hi Andrea, did you have any success or additional issues with the compilation?

**Comment by andrea-cassioli-maersk** [comment]
Hi @rstz , I did compile the protobuf but then I got some errors about missing `inc` files. I have put this on hold as it was a small side project. 

Honestly I have been surprised how complicated is to compile the library, I will probably give it a try in the future though.

**Comment by rstz** [comment]
Hi Andrea, that is unfortunate! Please feel free to ask additional questions if anything arises. We currently do not have the bandwidth to support CMake from our end, but I'd be very interested in getting it to work.

**Comment by andrea-cassioli-maersk** [comment]
Hi, I am back on this issue after long time. I am trying to follow
