### ISSUE TITLE
Issue on page /tutorial.html

### ISSUE THREAD

**Issue by hellomikelo** [google/yggdrasil-decision-forests#47]
In https://simplemlforsheets.com/tutorial.html#install-simple-ml-for-sheets, item 3 should remove "of", i.e. "Make a copy and open our [spreadsheet with example data](https://docs.google.com/spreadsheets/d/1Ve7umK4W6wBje1QZQVbPIH3djCl2uwfwXvezGliCpss/copy)."

**Comment by rstz** [comment]
Hi, thank you for reporting, a fix will land on the website soon!

**Comment by rstz** [comment]
Website now updated

**Comment by hpssjellis** [comment]
@rstz. This is amazing. If I make a video of it I will try to send you a link.
