### ISSUE TITLE
in which file you read all data sets from your paper

### ISSUE THREAD

**Issue by Sandy4321** [google/yggdrasil-decision-forests#49]
in which file you read all data sets from your paper 
https://arxiv.org/pdf/2212.02934.pdf
page 18
![image](https://github.com/google/yggdrasil-decision-forests/assets/11426119/cba6cf71-b2fd-4491-94e0-23ddb46680fa)

**Comment by rstz** [comment]
Question is unclear

**Comment by Sandy4321** [comment]
pls share python code to download all data sets from paper
my guess you do have some python code to automate for to download all data sets from paper
