### ISSUE TITLE
Documentation for using Go is out of date

### ISSUE THREAD

**Issue by jimidle** [google/yggdrasil-decision-forests#52]
The documentation indicates to use an import starting with "google3/...." but this needs to be:

```go

import (
	modelio "github.com/google/yggdrasil-decision-forests/yggdrasil_decision_forests/port/go/model/io/canonical"
	"github.com/google/yggdrasil-decision-forests/yggdrasil_decision_forests/port/go/serving"
)
```

Also the README and the current docs show using `model_io` as an import alias, but it is not idiomatic to use `_` in variables or aliess etc.

**Comment by rstz** [comment]
Hi, thank you for reporting this, I'll go over the Go documentation and fix this issue
