### ISSUE TITLE
Missing whitespace on page /cli_install.html and please use sudo in build_binary_release.sh

### ISSUE THREAD

**Issue by gl-yziquel** [google/yggdrasil-decision-forests#59]
Make the build a bit nicer for end-user:

In `https://ydf.readthedocs.io/en/latest/cli_install.html`, please add a space in `INSTALL_DEPENDENCIES=1 BUILD=1./tools/build_binary_release.sh` to make it `INSTALL_DEPENDENCIES=1 BUILD=1 ./tools/build_binary_release.sh`. This makes the build instruction a bit smoother...

And, then, please use `sudo` in that script when invoking `apt`. I indeed do not want to run `./tools/build_binary_release.sh` as root..

**Comment by gl-yziquel** [comment]
See https://github.com/google/yggdrasil-decision-forests/pull/60 for a fix for sudo.

**Comment by rstz** [comment]
Hi, thank you for reporting this. I'll add a fix for both problems soon. It's a tiny bit more complicated than your PR, since we sometimes run this script in environments without sudo, so I won't approve the PR and just fix the issue in a change of my own.

**Comment by gl-yziquel** [comment]
Thank you for taking this PR suggestion into account. I'll wait for your correction.

When you say that you sometimes run this script without sudo, do you mean that you run it as root on some, say, cloud environment ?

**Comment by rstz** [comment]
Mostly the build docker: tools/build_binary_release_in_docker.sh
