### ISSUE TITLE
Don't pollute my home !!

### ISSUE THREAD

**Issue by gl-yziquel** [google/yggdrasil-decision-forests#61]
Hi.

I compiled yggdrasil from source. And launched the beginner example.

It created a folder `yggdrasil_decision_forests_beginner` in my `$HOME`.

I guess this is a byproduct of the docker approach to builds. Ideally, what is built and tested in a folder dedicated to the project should stay in that project and not escape it.

(I mean, the bazel build is so cool, so local, so "hermetic"... That just kills the magic...)

**Comment by achoum** [comment]
The output files of the beginner example are saved in the "${HOME}/yggdrasil_decision_forests_beginner" directory. While this is not ideal, we made this decision for the following reasons:

- Parametrizing the output directory would make the example more complex to read and understand.
- The output directory is printed in the terminal, and the user is expected to open the generated .txt and .html files. We hope that the user will understand what this directory means and act accordingly (e.g., remove it when they are finished).
- Using a verbose and explicit directory name ("yggdrasil_decision_forests_beginner") ensures that the user understands what this directory is long after they have run the example (in case the user forgot to remove the directory).
- If the example is used multiple times, possibly on large datasets, using a temporary directory runs the risk of the directory not being removed until the next reboot, possibly using a large amount of the user's hard drive space unnoticed.

We hope that this explanation makes sense. If you have an alternative solution that is more competitive, we would be happy to consider it.
