### ISSUE TITLE
Cannot import ydf from windows vsc

### ISSUE THREAD

**Issue by ShadeChen** [google/yggdrasil-decision-forests#69]
Hi, I tried to install ydf via pip instdall ydf

It shows that I've install a version 0.0.5 of ydf.

when I'm trying to import ydf into the notebook, it pops up error showing as follows:

ImportError: cannot import name 'ydf' from 'ydf.cc' (c:\Users\**\AppData\Local\Programs\Python\Python311\Lib\site-packages\ydf\cc\__init__.py)

Any idea how I can fix this?

**Comment by rstz** [comment]
Hi,
thank you for trying out YDF. Can you please tell me more about your configuration? It looks like you're using Windows with Python 3.11 - yet we haven't released a Windows version for 0.0.5 - is this through WSL?

**Comment by ShadeChen** [comment]
Hi,

Currently I'm just runnig within Windows 11 Pro, not in WSL environment with python 3.11
I've tried pip uninstall ydf then pip install ydf again.
![屏幕截图 2023-11-29 100336](https://github.com/google/yggdrasil-decision-forests/assets/115678201/efccdcd3-6bee-4526-a033-778456b63e6d)
![屏幕截图 2023-11-29 100255](https://github.com/google/yggdrasil-decision-forests/assets/115678201/42d965b3-0b28-494e-91de-2280386238b2)

There is somehow another 0.0.6 of ydf here but still cannot import that into the notebook

**Comment by achoum** [comment]
Hi Shade,

Thank you for the details and your patience :).

YDF 0.0.5 was not released for Windows, which caused Windows pip to attempt (and fail) to compile YDF from the sources available on pypi. We will solve the situation in the next release.

A temporary solution that would have worked would have been to specify version 0.0.4, which had precompiled Windows support at the time.

The current version of YDF 0.0.7 has support for Windows, Linux and MacOS. Could you try again to run `pip install ydf -U` ?

**Comment by achoum** [comment]
@rstz 
I think we simply need to make sure the ydf-<version>.tar.gz  file is not uploaded to pypi.

**Comment by rstz** [comment]
Makes sense, I'll make sure that this file is no longer uploaded in future versions.

**Comment by JasperFrancois** [comment]
Hi @achoum and @rstz
I have installed the latest version of ydf (0.0.7) while working on Windows and I encounter the same issues ShadeChen described above.
![image](https://github.com/google/yggdrasil-decision-forests/assets/45099890/76b04812-934f-46d2-8a46-86121ddf1b71)
![image](https://github.com/google/yggdrasil-decision-forests/assets/45099890/58b18d26-84fb-4b54-b604-0d33ac8bcc28)
