### ISSUE TITLE
rich reports not rendering graphs in vscode

### ISSUE THREAD

**Issue by mocher72** [google/yggdrasil-decision-forests#74]
When running the example code in vscode .ipynb the graphs do not render.
I am using the cade the same as the tutorial.  https://ydf.readthedocs.io/en/latest/tutorial/getting_started/
After the evaluation cell no graphs are displayed.
When I try the same file in Jupyter lab backend with browser this is rendering OK.

I have tried this on both wsl and Macos arm64 and it is happening with both.

Is there any special setting i need to set?

**Comment by rstz** [comment]
Thanks for reporting. Looks like the plotly library is not loaded correctly, maybe for the reasons described here https://github.com/microsoft/vscode-jupyter/issues/13361

**Comment by mocher72** [comment]
I had a look into the renderer and have found if I uninstall the Jupyter Notebook Renderers extension, the graphs are now rendered!
https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter-renderers

I can confirm that this works on both wsl and macos arm64.

**Comment by rstz** [comment]
Cool, thank you for looking into it!
