### ISSUE TITLE
Converter from Yggdrasil model to TensorFlow SavedModel

### ISSUE THREAD

**Issue by janpfeifer** [google/yggdrasil-decision-forests#8]
Add a command line tool, such that a model (whenever possible) trained with Yggdrasil can easily be imported in a TensorFlow colab for exploration.

**Comment by achoum** [comment]
In the meantime:

1. Yggdrasil models can be converted into TF-DF models with the [tfdf.keras.core.yggdrasil_model_to_keras_model](https://www.tensorflow.org/decision_forests/api_docs/python/tfdf/keras/core/yggdrasil_model_to_keras_model). This method could be wrapper into a CLI.
2. Yggdrasil models are naively supported by the [TF-DF model inspector](https://www.tensorflow.org/decision_forests/api_docs/python/tfdf/inspector/make_inspector).
