### ISSUE TITLE
MHLD_OBLIQUE is unknown while mentioned in the documentation

### ISSUE THREAD

**Issue by lusis-ai** [google/yggdrasil-decision-forests#84]
When setting : `split_axis='MHLD_OBLIQUE'` in a Random Forest learner we get this error:

`ValueError: INVALID_ARGUMENT: Unknown value "MHLD_OBLIQUE" for the parameter "split_axis".`

**Comment by rstz** [comment]
Yep, the documentation landed too early - this was included in the docs yesterday, but will be in the next release only (it's only available at head

**Comment by rstz** [comment]
Fixed with the release of 0.3.0
