### ISSUE TITLE
NPM package for Javascript API

### ISSUE THREAD

**Issue by akshaan** [google/yggdrasil-decision-forests#94]
I'm using the Javascript API to run a decision forest model in a NodeJS server, and would like to include the code as an NPM dependency instead of bundling the minified JS and WASM files directly with the server source code. Are there any plans to publish an NPM package for this?

**Comment by achoum** [comment]
Yes, the publication of an npm is a work in progress.

I've pushed the current draft to npmjs. You can try it at:

https://www.npmjs.com/package/yggdrasil-decision-forests

Let me know if this works for you :)

**Comment by akshaan** [comment]
@achoum This worked perfectly, thanks!
